/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import Link from "next/link";
import { createOrder } from "@/action/order.action";
import { useRouter } from "next/navigation";

type CheckoutPageProps = {
  cartInfo: any;
};

export default function CheckoutPage({ cartInfo }: CheckoutPageProps) {
  const router = useRouter();
  const cart = cartInfo
    ? Array.isArray(cartInfo)
      ? cartInfo
      : [cartInfo]
    : [];

  const subtotal = cart.reduce(
    (sum, item) => sum + (item.medicines?.price || 0) * (item.quantity || 0),
    0,
  );

  const [address, setAddress] = useState("");
  const [paymentMethod, setPaymentMethod] = useState("COD"); // ডিফল্ট 'COD' বা 'STRIPE'
  const [loading, setLoading] = useState(false);

  const handlePlaceOrder = async () => {
    if (cart.length === 0) {
      toast.error("Your cart is empty!");
      return;
    }

    if (!address.trim()) {
      toast.error("Please enter your delivery address");
      return;
    }

    setLoading(true);
    const toastId = toast.loading("Processing your order...");

    const data = {
      paymentGateway: paymentMethod, // "COD" অথবা "STRIPE"
      shippingAddress: address,
    };

    console.log("Sending data to action:", data);

    try {
      const res = (await createOrder(data)) as any;
      console.log("Exact Response from server action:", res);

      const stripeUrl = res?.data?.paymentUrl || res?.paymentUrl;

      if (paymentMethod === "STRIPE") {
        if (stripeUrl) {
          toast.success("Redirecting to Stripe payment gateway...", {
            id: toastId,
          });
          console.log("Redirecting to Stripe URL:", stripeUrl);

          window.location.href = stripeUrl;
        } else {
          toast.error("Stripe payment URL was not generated by server.", {
            id: toastId,
          });
        }
      }
      // 💵 পেমেন্ট গেটওয়ে যদি COD হয়
      else {
        toast.success("Order placed successfully!", { id: toastId });
        router.push("/shop");
      }
    } catch (error) {
      console.error("Order process execution error:", error);
      toast.error("An unexpected error occurred", { id: toastId });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold mb-6">Checkout</h1>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Delivery Details & Payment Selection */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <h2 className="text-xl font-semibold mb-4">Delivery Details</h2>

          <label className="block mb-3">
            <span className="text-gray-700 font-medium text-sm">
              Delivery Address
            </span>
            <textarea
              className="mt-1 block w-full border rounded-lg p-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
              rows={4}
              placeholder="Enter your full street address, apartment, city, and zip code"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
            />
          </label>

          <h2 className="text-xl font-semibold mt-6 mb-3">Payment Method</h2>
          <div className="space-y-2">
            <label className="flex items-center gap-3 p-3 border rounded-lg cursor-pointer hover:bg-gray-50 transition">
              <input
                type="radio"
                name="payment"
                value="COD"
                checked={paymentMethod === "COD"}
                onChange={() => setPaymentMethod("COD")}
                className="w-4 h-4 text-primary"
              />
              <span className="text-sm font-medium text-gray-800">
                Cash on Delivery
              </span>
            </label>

            <label className="flex items-center gap-3 p-3 border rounded-lg cursor-pointer hover:bg-gray-50 transition">
              <input
                type="radio"
                name="payment"
                value="STRIPE"
                checked={paymentMethod === "STRIPE"}
                onChange={() => setPaymentMethod("STRIPE")}
                className="w-4 h-4 text-primary"
              />
              <span className="text-sm font-medium text-gray-800">
                Stripe (Card Payment)
              </span>
            </label>
          </div>
        </div>

        {/* Order Summary */}
        <div className="bg-primary/10 p-6 rounded-xl shadow-sm self-start">
          <h2 className="text-xl font-semibold mb-4 text-gray-900">
            Order Summary
          </h2>

          <div className="space-y-3 max-h-60 overflow-y-auto pr-1">
            {cart.map((item) => (
              <div
                key={item.id}
                className="flex justify-between items-center text-sm"
              >
                <div className="text-gray-700">
                  <span className="font-medium text-gray-950">
                    {item.medicines?.name}
                  </span>
                  <span className="text-gray-500 text-xs block">
                    Qty: {item.quantity}
                  </span>
                </div>
                <div className="font-semibold text-gray-900">
                  $
                  {(
                    (item.medicines?.price || 0) * (item.quantity || 0)
                  ).toFixed(2)}
                </div>
              </div>
            ))}
          </div>

          <div className="border-t border-primary/20 mt-4 pt-4 flex justify-between text-lg font-bold text-gray-900">
            <span>Total:</span>
            <span>${subtotal.toFixed(2)}</span>
          </div>

          <Button
            size="lg"
            className="w-full mt-6 text-base font-semibold"
            onClick={handlePlaceOrder}
            disabled={loading}
          >
            {loading
              ? "Processing..."
              : paymentMethod === "STRIPE"
                ? "Proceed to Payment"
                : "Place Order (COD)"}
          </Button>

          <Link
            href="/medicines"
            className="block text-center mt-4 text-sm font-medium text-primary hover:underline"
          >
            ← Continue Shopping
          </Link>
        </div>
      </div>
    </div>
  );
}
